### ISSUE TITLE
Missing dependencies during installation

### ISSUE THREAD

**Issue by freaz** [apiaryio/black-belt#91] opened 2015-05-04 20:47 UTC
After clean installation through pip the bb command complains about missing module __slacker__.

The slacker module is in requirements, but probably is not installed by pip.

Manual installation fixes the issue.

**Comment by Almad** [comment] 2015-05-14 15:56
Can you verify it's fixed by #90 plz?

**Comment by honzajavorek** [comment] 2015-05-14 21:37
I was affected by this bug too and I can't reproduce it anymore.

**Comment by abtris** [comment] 2015-05-15 04:42
ok, I close.

**Closed by abtris** 2015-05-15 04:42 UTC
Labels: bug

**Comment by freaz** [comment] 2015-05-15 08:51
Yes, works for me too.
