### ISSUE TITLE
Deploy crashes at the end

### ISSUE THREAD

**Issue by miiila** [apiaryio/black-belt#121] opened 2016-09-17 10:43 UTC
Root cause N/A, need to investigate.

```
Moving card failed. Open PR in browser? [True]: False
{u'documentation_url': u'https://developer.github.com/v3/repos/deployments/#create-a-deployment', u'message': u'No ref found for: miiila/another-bugfix-for-sales-report'}
Traceback (most recent call last):
  File "/usr/local/bin/bb", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/blackbelt/tasks.py", line 32, in main
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/commands/gh.py", line 50, in deploy
    deploy_command(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/commands/gh.py", line 59, in deploy_command
    do_deploy(pr_url)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/handle_github.py", line 300, in deploy
    create_release(ref=merge_info['branch'], payload='', description="Deployed to production", repo_info=repo_info)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/handle_github.py", line 321, in create_release
    raise ValueError("Create github release ended with status code %s: %s" % (r.status_code, r))
ValueError: Create github release ended with status code 422: <Response [422]>
```

**Comment by XVincentX** [comment] 2016-09-17 11:29
It's because we're using the github deployment/release API in the wrong way.

To be honest, I coded that part but it seems like the things changed after a while and given that's Python, I was to lazy to step in.

**Comment by honzajavorek** [comment] 2018-06-29 13:58
Duplicate of https://github.com/apiaryio/black-belt/issues/111

**Closed by honzajavorek** 2018-06-29 13:58 UTC
